### ISSUE TITLE
Fatal DB Error.

### ISSUE THREAD

**Issue by iwyg** [animaux/uniqueindex#1]
I experience DB Error (when creating  an entry) if unique index is used on a section that contains a multilingual textfield.    

`SELECT SQL_CACHE sym_entries_data_32.entry_id FROM sym_entries_data_32 WHERE sym_entries_data_32.entry_id = sym_entries_data_32.entry_id AND`

Seems like SQL query is messed up.

**Comment by animaux** [comment]
Same goes if used with an `association_field`.

**Comment by animaux** [comment]
Workaround is to use a `reflection-field` that extracts the id from the associated entry, e. g. `{entry/association-field/item/@id}` and then to use that field for the uniqueness-check. Not sure if that would work for multiple associated entries.

**Comment by animaux** [comment]
An even better fix, add: 

          case 'association':
                    $value_field = 'relation_id';
                    break;

**Comment by animaux** [comment]
Lacking info if the problem persists with current versions I’m closing this. Feel free to open again if the error pops up again.
